name: ${artifactId}
version: ${version}
main: ${main.class}
permissions:
  vb.admin:
    description: Allows administration of Volleyball
    default: op
  vb.help:
    description: Allows the use of the '/vb help' command.
    default: true
commands: