name: ${artifactId}
version: ${version}
main: ${main.class}
depend: [WorldEdit]
permissions:
  vb.admin:
    description: Allows administration of Volleyball
    default: op
  vb.user:
    description: Allows the use of Volleyball courts, but not teleportation features.
    default: true
  vb.tp:
    description: Allows the use of court teleportation features.
    default: true
commands: